### PR TITLE
Update project to Rxjava 2

### PR DESCRIPTION
**Pull request by anasanasanas**
projects consume InstaCupture with Rxjava 1 need to use
https://github.com/akarnokd/RxJava2Interop

### CODE REVIEW

**Comment by tarek360** [comment]
@anasanasanas 

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxjava.properties
  	File1: /Users/tarek/.gradle/caches/modules-2/files-2.1/io.reactivex.rxjava2/rxjava/2.0.3/d2f725668bd22e21170381b23f8fbdf72c69d886/rxjava-2.0.3.jar
  	File2: /Users/tarek/.gradle/caches/modules-2/files-2.1/io.reactivex/rxjava/1.2.4/522cfb00b6c015b72c64ee60054b4f6338880858/rxjava-1.2.4.jar
```

**Comment by tarek360** [comment]
@anasanasanas It builds successfully now, but this PR will make InstaCupture depends on RxJava1, RxJava2, and RxJava2Interop, this will increase the app methods count by
RxJava1 ≈ 5K    **+**   RxJava2 ≈ 10K + RxJava2Interop = ??
Total ≈ +15K, a lot of developers will hate this matter.

If you want to update InstaCupture to RxJava2, I think you have two options
1- Make it in new flavor
2- Create a new branch for RxJava1 then update the `develop` branch to RxJava2

**Comment by anasanasanas** [comment]
hello @tarek360,
I believe the second option make more sense, I will work on it in my free time.
Thank you.

**Comment by tarek360** [comment]
@anasanasanas I will close this PR and I will wait your​ new PR at any time, thank​ you.

**Pull request closed without merging**
